version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    depends_on:
      - redis
      - worker
  redis:
    image: redis
    ports:
      - 6379:6379
  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
