version: "3"

services:
  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    container_name: flask
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    depends_on:
      - redis

  redis:
    build:
      context: .
      dockerfile: redis.Dockerfile
    container_name: redis
    ports:
      - 6379:6379
