version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - db
    networks:
      - flask
  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:3.13-management
    ports:
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=flask
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - flask
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'celery'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - flask
  worker:
    container_name: flask_worker
    build: .
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - db
      - rabbitmq
    networks:
      - flask

networks:
  flask:
    driver: bridge